### ISSUE TITLE
Create a route for SendGrid and initialize SendGrid api

### ISSUE THREAD

**Issue by ANISH0309** [ACM-VIT/maildart-backend#8]
Add the route to the routes folder and run an example function for the same

**Comment by anandamideShakyan** [comment]
I would like to work on this issue , thank you .

**Comment by ANISH0309** [comment]
> I would like to work on this issue , thank you .

Hey, assigning you this issue.

**Comment by 1407arjun** [comment]
@ANISH0309 If the issue isnt resolved still, can I take it up?

**Comment by ANISH0309** [comment]
> @ANISH0309 If the issue isnt resolved still, can I take it up?

Sure, you can take on this issue, best of luck.
